# Replace the "❯" symbol in the prompt with "➜"
#[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
#error_symbol = "[✗](bold red) "

# move time to first line
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$time\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[nodejs]
disabled = true

[package]
disabled = true

[directory]
truncation_length = 0 # don't truncate path

[time]
disabled = false
format="at [$time]($style) "

